letterRead: newRandChars.o randChar.o letterRead.c
	gcc newRandChars.o randChar.o letterRead.c -lm -o letterRead

newRandChars.o : newRandChars.c
	gcc newRandChars.c -c

randChar.o : randChar.c
	gcc randChar.c -c
