#include <stdio.h>
#include <stdlib.h>
#include <math.h>

/**
* The formula used to generate the psudeorandom numbers.
**/
int lcg( int seed, int mod ) {
  return (2 * seed + 3) % mod;
}

/**
* Generates the random numbers and then checks to see if they appear random
**/
int main( int argc, char *argv[] ) {
  int seed = 5; //starting number if not defined in command line
  int i;
  float num;
  int mod = 100; //the modulus
  float average; //the average to check if the numbers were random and evenly distributed
  float sum = 0; //the sum of all random numbers generated
  int len = 100; //the amount of numbers generated

  /**
  * 1st argument is the seed of the random number generator
  **/
  if (argc > 1) {
    seed = atoi(argv[1]);
  }

  /**
  * 2nd argumnet is the amount of numbers generated
  **/
  if (argc > 2) {
    len = atoi(argv[2]);
  }

  /**
  * Takes the number generated by the formula. Puts it between 0 and 1.
  * Then puts the number generated in the formula back  agin to generate another number.
  * Sum continues to calculate all the numbers generated.
  **/
  for (i = 0; i <= len; i++) {
    num = (float)seed/mod;
    sum = sum + num;
    printf("%6.2f ", num);
    seed = lcg(seed, mod);
  }

  average = (float)sum/len; //calculated the average

  printf("...\n");
  printf("The sum of all the numbers is %6.2f\n", sum);
  printf("The average is %6.2f\n", average);

  //checks to see if the numbers are random or not.
  if (average <= 0.55 && average >= 0.45) {
    printf("These numbers were random\n");
  }
  else {
    printf("These numbers weren't random\n");
  }

  return 0;

}
